# Generated by Django 5.1.7 on 2025-03-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('HI_NREG', models.IntegerField(primary_key=True, serialize=False)),
                ('HI_AUTASE', models.CharField(max_length=255)),
                ('HI_NOMBRE', models.CharField(max_length=255)),
                ('HI_FECNAC', models.DateField()),
                ('HI_UBINAC', models.CharField(default='SIN DATOS', max_length=255)),
                ('HI_DIRECC', models.CharField(max_length=255)),
                ('HI_SEXO', models.CharField(max_length=255)),
                ('HI_NDOCUM', models.CharField(default='SIN DATOS', max_length=20, unique=True)),
                ('HI_ESTCIV', models.CharField(max_length=255)),
                ('HI_CPOLIC', models.CharField(default='valor_por_defecto', max_length=255)),
            ],
        ),
    ]
