# Generated by Django 5.1.7 on 2025-03-11 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDeSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('es_principal', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='cupo',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='hospital',
        ),
        migrations.AddField(
            model_name='cupo',
            name='centro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cupos', to='citas.centrodesalud'),
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('Medico', 'Médico'), ('Terminalista', 'Terminalista')], max_length=100)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='citas.centrodesalud')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cupo',
            name='medico',
            field=models.ForeignKey(limit_choices_to={'cargo': 'Medico'}, on_delete=django.db.models.deletion.CASCADE, to='citas.personal'),
        ),
        migrations.DeleteModel(
            name='HospitalPrincipal',
        ),
        migrations.DeleteModel(
            name='Medico',
        ),
    ]
