# Generated by Django 5.1.7 on 2025-03-12 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_centrodesalud_remove_cupo_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupo',
            name='estado',
            field=models.CharField(default='PROGRAMACION', max_length=20),
        ),
        migrations.AddField(
            model_name='cupo',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cupo',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupos_registrados', to='citas.personal'),
        ),
        migrations.AlterField(
            model_name='cupo',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupos', to='citas.centrodesalud'),
        ),
    ]
