# Generated by Django 5.1.7 on 2025-03-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_cupo_estado_cupo_fecha_registro_cupo_registrado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='cargo',
            field=models.CharField(choices=[('Medico', 'Medico'), ('Terminalista', 'Terminalista'), ('Programador', 'Programador')], max_length=100),
        ),
    ]
