# Generated by Django 5.1.7 on 2025-04-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_cita_numero_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodesalud',
            name='direccion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
