# Generated by Django 5.1.7 on 2025-04-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_centrodesalud_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='atendido',
            field=models.BooleanField(default=False),
        ),
    ]
